
import { Patient, Gender, MaritalStatus, Handedness, Contraception } from "@/types";

export const adaptPatientFromSupabase = (data: any): Patient => ({
  id: data.id,
  createdAt: data.created_at || data.createdAt,
  updatedAt: data.updated_at || data.updatedAt,
  firstName: data.firstName,
  lastName: data.lastName,
  email: data.email,
  phone: data.phone,
  address: data.address,
  gender: data.gender as Gender,
  birthDate: data.birthDate,
  maritalStatus: data.maritalStatus as MaritalStatus,
  occupation: data.occupation,
  hasChildren: data.hasChildren,
  childrenAges: data.childrenAges,
  generalPractitioner: data.generalPractitioner,
  surgicalHistory: data.surgicalHistory,
  traumaHistory: data.traumaHistory,
  rheumatologicalHistory: data.rheumatologicalHistory,
  currentTreatment: data.currentTreatment,
  handedness: data.handedness as Handedness,
  hasVisionCorrection: data.hasVisionCorrection,
  ophtalmologistName: data.ophtalmologistName,
  entProblems: data.entProblems,
  entDoctorName: data.entDoctorName,
  digestiveProblems: data.digestiveProblems,
  digestiveDoctorName: data.digestiveDoctorName,
  physicalActivity: data.physicalActivity,
  isSmoker: data.isSmoker,
  isExSmoker: data.isExSmoker || false,
  smokingSince: data.smokingSince || null,
  smokingAmount: data.smokingAmount || null,
  quitSmokingDate: data.quitSmokingDate || null,
  isDeceased: data.isDeceased,
  contraception: data.contraception as Contraception,
  hdlm: data.hdlm,
  avatarUrl: data.avatarUrl,
  cabinetId: data.cabinetId,
  userId: data.userId || null,
  osteopathId: data.osteopathId || 1,
  // Ajout du champ familyStatus
  familyStatus: data.familyStatus || null,
  // Champs existants pour tous les patients
  complementaryExams: data.complementaryExams || null,
  generalSymptoms: data.generalSymptoms || null,
  // Champs existants pour les enfants
  pregnancyHistory: data.pregnancyHistory || null,
  birthDetails: data.birthDetails || null,
  developmentMilestones: data.developmentMilestones || null,
  sleepingPattern: data.sleepingPattern || null,
  feeding: data.feeding || null,
  behavior: data.behavior || null,
  childCareContext: data.childCareContext || null,
  
  // Nouveaux champs généraux
  ent_followup: data.ent_followup || null,
  intestinal_transit: data.intestinal_transit || null,
  sleep_quality: data.sleep_quality || null,
  fracture_history: data.fracture_history || null,
  dental_health: data.dental_health || null,
  sport_frequency: data.sport_frequency || null,
  gynecological_history: data.gynecological_history || null,
  other_comments_adult: data.other_comments_adult || null,
  
  // Nouveaux champs spécifiques aux enfants
  fine_motor_skills: data.fine_motor_skills || null,
  gross_motor_skills: data.gross_motor_skills || null,
  weight_at_birth: data.weight_at_birth || null,
  height_at_birth: data.height_at_birth || null,
  head_circumference: data.head_circumference || null,
  apgar_score: data.apgar_score || null,
  childcare_type: data.childcare_type || null,
  school_grade: data.school_grade || null,
  pediatrician_name: data.pediatrician_name || null,
  paramedical_followup: data.paramedical_followup || null,
  other_comments_child: data.other_comments_child || null,
});
