import { DemoStorage } from './demo-storage';
import { Patient, Appointment, Invoice, Cabinet } from '@/types';

/**
 * 🌱 Génère des données de démonstration avec des dates dynamiques
 *
 * Cette fonction est appelée à chaque chargement de page pour garantir que :
 * - Les rendez-vous passés couvrent toujours les 12 derniers mois
 * - Les rendez-vous futurs sont toujours dans le futur (J+1 à J+14)
 * - Les factures correspondent aux rendez-vous avec des dates cohérentes
 * - Les statistiques du dashboard restent pertinentes même après plusieurs mois
 *
 * Les données sont régénérées dynamiquement basées sur new Date() actuelle.
 */
export function seedDemoData(cabinetId: string, userId: string, cabinetName: string): void {
  const now = new Date();

  // Données ostéopathe démo (pour affichage lecture seule)
  const demoOsteopath = {
    id: userId,
    userId: userId,
    name: 'Dr. Utilisateur Démo',
    professional_title: 'Ostéopathe D.O.',
    rpps_number: '10001234567',
    siret: '12345678900012',
    ape_code: '8690F',
    plan: 'demo' as const,
    status: 'demo' as const,
    demo_started_at: now.toISOString(),
    createdAt: now.toISOString(),
    updatedAt: now.toISOString()
  };

  const cabinet: Cabinet = {
    id: cabinetId,
    name: cabinetName,
    address: '12 Rue de la République',
    city: 'Toulouse',
    postalCode: '31000',
    phone: '05 61 00 00 00',
    email: 'demo@osteopraxis.fr',
    siret: '12345678900012',
    iban: null,
    bic: null,
    country: 'France',
    osteopathId: userId,
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    imageUrl: null
  };

  // 10 patients démo avec données variées (incluant 2 enfants)
  const patients: Patient[] = [
    {
      id: crypto.randomUUID(),
      firstName: 'Jean',
      lastName: 'Dupont',
      gender: 'Homme',
      email: 'jean.dupont@example.com',
      phone: '06 12 34 56 78',
      birthDate: '1985-05-15',
      address: '5 Avenue des Champs',
      city: 'Toulouse',
      postalCode: '31000',
      osteopathId: userId,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      // Données médicales adulte
      height: 178,
      weight: 82,
      bmi: 25.9,
      allergies: 'Pollen de bouleau',
      currentTreatment: 'Antihistaminiques (Cetirizine 10mg) en saison allergique',
      isSmoker: false,
      isExSmoker: true,
      quitSmokingDate: '2020-03-15',
      smokingAmount: '10 cigarettes/jour pendant 8 ans',
      maritalStatus: 'MARRIED',
      occupation: 'Ingénieur informatique',
      physicalActivity: 'Course à pied 3x/semaine',
      hasChildren: 'Oui (2 enfants)',
      handedness: 'RIGHT',
      generalPractitioner: 'Dr. Lefevre',
      surgicalHistory: 'Appendicectomie (2005)',
      traumaHistory: 'Entorse cheville droite (2018)',
      rheumatologicalHistory: 'Lombalgie chronique depuis 2019',
      entProblems: 'Rhinite allergique saisonnière',
      digestiveProblems: 'RAS',
      ent_followup: 'Suivi allergologique annuel',
      intestinal_transit: 'Normal',
      sleep_quality: 'Bon (7-8h/nuit)',
      sport_frequency: '3-4 fois/semaine',
      dental_health: 'Suivi régulier, dernière visite il y a 6 mois',
      fracture_history: 'Aucune',
      other_comments_adult: 'Travail sur écran prolongé, tensions cervicales récurrentes',
      hasVisionCorrection: true,
      avatarUrl: null,
      cabinetId: null,
      userId: null
    },
    {
      id: crypto.randomUUID(),
      firstName: 'Marie',
      lastName: 'Martin',
      gender: 'Femme',
      email: 'marie.martin@example.com',
      phone: '06 98 76 54 32',
      birthDate: '1990-08-22',
      address: '8 Boulevard Victor Hugo',
      city: 'Toulouse',
      postalCode: '31000',
      osteopathId: userId,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      // Données médicales adulte femme
      height: 165,
      weight: 58,
      bmi: 21.3,
      allergies: 'Pénicilline, arachides',
      currentTreatment: 'Pilule contraceptive (Leeloo Gé)',
      isSmoker: false,
      isExSmoker: false,
      maritalStatus: 'SINGLE',
      occupation: 'Professeur des écoles',
      physicalActivity: 'Yoga 2x/semaine, natation occasionnelle',
      hasChildren: 'Non',
      handedness: 'LEFT',
      generalPractitioner: 'Dr. Moreau',
      contraception: 'PILLS',
      contraception_notes: 'Depuis 2012, aucun effet secondaire notable',
      surgicalHistory: 'RAS',
      traumaHistory: 'Fracture poignet gauche (2015)',
      rheumatologicalHistory: 'RAS',
      entProblems: 'RAS',
      digestiveProblems: 'Légère intolérance au lactose',
      gynecological_history: 'Cycles réguliers, dysménorrhée modérée',
      ent_followup: 'RAS',
      intestinal_transit: 'Normal avec régime sans lactose',
      sleep_quality: 'Moyen (réveils nocturnes fréquents)',
      sport_frequency: '2-3 fois/semaine',
      dental_health: 'Excellent, orthodontie terminée en 2010',
      fracture_history: 'Poignet gauche (2015)',
      other_comments_adult: 'Migraines menstruelles récurrentes, gestion par relaxation',
      hasVisionCorrection: true,
      avatarUrl: null,
      cabinetId: null,
      userId: null
    },
    {
      id: crypto.randomUUID(),
      firstName: 'Pierre',
      lastName: 'Durand',
      gender: 'Homme',
      email: 'pierre.durand@example.com',
      phone: '06 45 67 89 01',
      birthDate: '1978-11-30',
      address: '15 Rue Jean Jaurès',
      city: 'Toulouse',
      postalCode: '31000',
      osteopathId: userId,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      height: 185,
      weight: 95,
      bmi: 27.8,
      allergies: 'Aucune allergie connue',
      currentTreatment: 'Metformine 850mg (diabète type 2), Ramipril 5mg (HTA)',
      isSmoker: true,
      smokingAmount: '15 cigarettes/jour depuis 25 ans',
      maritalStatus: 'DIVORCED',
      occupation: 'Chauffeur routier',
      physicalActivity: 'Marche occasionnelle',
      hasChildren: 'Oui (3 enfants)',
      handedness: 'RIGHT',
      generalPractitioner: 'Dr. Dubois',
      surgicalHistory: 'Hernie discale L4-L5 (2016), prothèse hanche gauche (2022)',
      traumaHistory: 'Accident voiture avec whiplash (2014)',
      rheumatologicalHistory: 'Arthrose lombaire et cervicale, gonarthrose bilatérale',
      cardiac_history: 'HTA traitée depuis 2018',
      digestiveProblems: 'Reflux gastro-œsophagien',
      intestinal_transit: 'Constipation chronique',
      sleep_quality: 'Mauvais (apnées du sommeil suspectées)',
      sport_frequency: 'Rare',
      dental_health: 'Plusieurs caries non traitées',
      fracture_history: 'Fracture tibia-péroné droite (1998)',
      other_comments_adult: 'Surpoids, sédentarité professionnelle, douleurs lombaires chroniques',
      hasVisionCorrection: true,
      avatarUrl: null,
      cabinetId: null,
      userId: null
    },
    {
      id: crypto.randomUUID(),
      firstName: 'Sophie',
      lastName: 'Bernard',
      gender: 'Femme',
      email: 'sophie.bernard@example.com',
      phone: '06 23 45 67 89',
      birthDate: '1982-03-10',
      address: '22 Rue Lafayette',
      city: 'Toulouse',
      postalCode: '31000',
      osteopathId: userId,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      height: 172,
      weight: 68,
      bmi: 23.0,
      allergies: 'Latex, parfums synthétiques',
      currentTreatment: 'Lévothyroxine 75µg (hypothyroïdie), Magnésium B6',
      isSmoker: false,
      isExSmoker: false,
      maritalStatus: 'MARRIED',
      occupation: 'Kinésithérapeute',
      physicalActivity: 'Pilates 3x/semaine, randonnée le weekend',
      hasChildren: 'Oui (2 enfants)',
      handedness: 'RIGHT',
      generalPractitioner: 'Dr. Martin',
      contraception: 'IUD',
      contraception_notes: 'DIU au cuivre depuis 2016',
      surgicalHistory: '2 césariennes (2012, 2015)',
      gynecological_history: 'Endométriose diagnostiquée en 2010, sous contrôle',
      traumaHistory: 'Entorse genou droit (2019)',
      rheumatologicalHistory: 'Tendinite épaule droite récidivante',
      digestiveProblems: 'Syndrome côlon irritable',
      intestinal_transit: 'Irrégulier, alternance diarrhée/constipation',
      sleep_quality: 'Bon (utilise techniques de relaxation)',
      sport_frequency: '4-5 fois/semaine',
      dental_health: 'Bon suivi, gingivite légère',
      fracture_history: 'Aucune',
      other_comments_adult: 'Excellente connaissance anatomie, auto-rééducation efficace',
      hasVisionCorrection: false,
      avatarUrl: null,
      cabinetId: null,
      userId: null
    },
    {
      id: crypto.randomUUID(),
      firstName: 'Lucas',
      lastName: 'Petit',
      gender: 'Homme',
      email: 'lucas.petit@example.com',
      phone: '06 34 56 78 90',
      birthDate: '1995-07-18',
      address: '7 Place du Capitole',
      city: 'Toulouse',
      postalCode: '31000',
      osteopathId: userId,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      height: 175,
      weight: 72,
      bmi: 23.5,
      allergies: 'Aucune',
      currentTreatment: 'Aucun traitement régulier',
      isSmoker: false,
      isExSmoker: false,
      maritalStatus: 'PARTNERED',
      occupation: 'Développeur web',
      physicalActivity: 'Escalade 2x/semaine, vélo quotidien',
      hasChildren: 'Non',
      handedness: 'AMBIDEXTROUS',
      generalPractitioner: 'Dr. Rousseau',
      surgicalHistory: 'RAS',
      traumaHistory: 'Entorse poignet droit escalade (2021)',
      rheumatologicalHistory: 'RAS',
      entProblems: 'Acouphènes légers (exposition musique forte)',
      digestiveProblems: 'RAS',
      intestinal_transit: 'Normal',
      sleep_quality: 'Variable (travail parfois de nuit)',
      sport_frequency: '3-4 fois/semaine',
      dental_health: 'Excellent, jamais de carie',
      fracture_history: 'Aucune',
      other_comments_adult: 'Excellente condition physique, tensions trapèzes liées au travail écran',
      hasVisionCorrection: false,
      avatarUrl: null,
      cabinetId: null,
      userId: null
    },
    {
      id: crypto.randomUUID(),
      firstName: 'Emma',
      lastName: 'Roux',
      gender: 'Femme',
      email: 'emma.roux@example.com',
      phone: '06 56 78 90 12',
      birthDate: '1988-12-05',
      address: '33 Allée Jean Jaurès',
      city: 'Toulouse',
      postalCode: '31000',
      osteopathId: userId,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      height: 168,
      weight: 64,
      bmi: 22.7,
      allergies: 'Pollen de graminées, acariens',
      currentTreatment: 'Loratadine 10mg (allergie), Spray nasal corticoïde',
      isSmoker: false,
      isExSmoker: false,
      maritalStatus: 'SINGLE',
      occupation: 'Avocate',
      physicalActivity: 'Tennis 1x/semaine, running occasionnel',
      hasChildren: 'Non',
      handedness: 'RIGHT',
      generalPractitioner: 'Dr. Bernard',
      contraception: 'PATCH',
      surgicalHistory: 'Appendicectomie (2008), ablation kyste ovarien (2019)',
      traumaHistory: 'Entorse cheville gauche tennis (2020)',
      gynecological_history: 'Cycles réguliers, kyste ovarien fonctionnel récidivant',
      rheumatologicalHistory: 'Tendinite épaule gauche (2021)',
      entProblems: 'Rhinite allergique chronique',
      digestiveProblems: 'RAS',
      ent_followup: 'Allergologue annuellement',
      intestinal_transit: 'Normal',
      sleep_quality: 'Moyen (stress professionnel, insomnies)',
      sport_frequency: '2 fois/semaine',
      dental_health: 'Suivi régulier, bruxisme nocturne (port gouttière)',
      fracture_history: 'Aucune',
      other_comments_adult: 'Stress élevé, tensions cervico-dorsales, céphalées de tension',
      hasVisionCorrection: true,
      avatarUrl: null,
      cabinetId: null,
      userId: null
    },
    {
      id: crypto.randomUUID(),
      firstName: 'Thomas',
      lastName: 'Moreau',
      gender: 'Homme',
      email: 'thomas.moreau@example.com',
      phone: '06 67 89 01 23',
      birthDate: '1992-09-14',
      address: '18 Rue Alsace Lorraine',
      city: 'Toulouse',
      postalCode: '31000',
      osteopathId: userId,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      height: 180,
      weight: 76,
      bmi: 23.5,
      allergies: 'Piqûres d\'abeille (réaction sévère)',
      currentTreatment: 'EpiPen (urgence allergie)',
      isSmoker: false,
      isExSmoker: true,
      quitSmokingDate: '2019-01-01',
      smokingAmount: '5 cigarettes/jour pendant 4 ans',
      maritalStatus: 'ENGAGED',
      occupation: 'Architecte',
      physicalActivity: 'Salle de sport 4x/semaine, trail running',
      hasChildren: 'Non',
      handedness: 'RIGHT',
      generalPractitioner: 'Dr. Fontaine',
      surgicalHistory: 'Ligamentoplastie genou droit (2017)',
      traumaHistory: 'Rupture LCA genou droit football (2017)',
      rheumatologicalHistory: 'Arthrose débutante genou droit post-trauma',
      entProblems: 'RAS',
      digestiveProblems: 'RAS',
      intestinal_transit: 'Normal',
      sleep_quality: 'Excellent (8-9h/nuit)',
      sport_frequency: '5-6 fois/semaine',
      dental_health: 'Très bon',
      fracture_history: 'Clavicule gauche vélo (2015)',
      other_comments_adult: 'Sportif assidu, légères douleurs genou après effort intense',
      hasVisionCorrection: false,
      avatarUrl: null,
      cabinetId: null,
      userId: null
    },
    {
      id: crypto.randomUUID(),
      firstName: 'Chloé',
      lastName: 'Simon',
      gender: 'Femme',
      email: 'chloe.simon@example.com',
      phone: '06 78 90 12 34',
      birthDate: '1987-04-28',
      address: '9 Rue de Metz',
      city: 'Toulouse',
      postalCode: '31000',
      osteopathId: userId,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      height: 160,
      weight: 52,
      bmi: 20.3,
      allergies: 'Nickel (bijoux), kiwi',
      currentTreatment: 'Aucun',
      isSmoker: false,
      isExSmoker: false,
      maritalStatus: 'MARRIED',
      occupation: 'Graphiste freelance',
      physicalActivity: 'Danse contemporaine 2x/semaine',
      hasChildren: 'Oui (1 enfant)',
      handedness: 'LEFT',
      generalPractitioner: 'Dr. Petit',
      contraception: 'NATURAL_METHODS',
      surgicalHistory: 'Césarienne (2020)',
      gynecological_history: 'Accouchement par césarienne, cicatrice adhérente',
      traumaHistory: 'RAS',
      rheumatologicalHistory: 'Hyperlaxité ligamentaire généralisée',
      entProblems: 'Vertiges positionnels occasionnels',
      digestiveProblems: 'RAS',
      intestinal_transit: 'Normal',
      sleep_quality: 'Moyen (réveil nocturne enfant)',
      sport_frequency: '2-3 fois/semaine',
      dental_health: 'Bon',
      fracture_history: 'Aucune',
      other_comments_adult: 'Douleurs lombaires post-partum, travail prolongé sur tablette graphique',
      hasVisionCorrection: true,
      avatarUrl: null,
      cabinetId: null,
      userId: null
    },
    {
      id: crypto.randomUUID(),
      firstName: 'Alexandre',
      lastName: 'Laurent',
      gender: 'Homme',
      email: 'alexandre.laurent@example.com',
      phone: '06 89 01 23 45',
      birthDate: '1980-11-20',
      address: '44 Avenue de la Gloire',
      city: 'Toulouse',
      postalCode: '31000',
      osteopathId: userId,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      height: 172,
      weight: 78,
      bmi: 26.4,
      allergies: 'Amoxicilline',
      currentTreatment: 'Atorvastatine 20mg (cholestérol), Aspirine 75mg',
      isSmoker: false,
      isExSmoker: true,
      quitSmokingDate: '2015-06-10',
      smokingAmount: '20 cigarettes/jour pendant 20 ans',
      maritalStatus: 'WIDOWED',
      occupation: 'Chef d\'entreprise (BTP)',
      physicalActivity: 'Golf 1x/semaine',
      hasChildren: 'Oui (4 enfants)',
      handedness: 'RIGHT',
      generalPractitioner: 'Dr. Dupuis',
      surgicalHistory: 'Pontage coronarien (2019), hernie inguinale (2010)',
      traumaHistory: 'Chute échafaudage avec fractures multiples (2005)',
      cardiac_history: 'Infarctus myocarde 2019, pontage triple, suivi cardiologique régulier',
      rheumatologicalHistory: 'Arthrose lombaire sévère, canal carpien bilatéral opéré',
      digestiveProblems: 'RAS',
      intestinal_transit: 'Normal',
      sleep_quality: 'Moyen (douleurs nocturnes)',
      sport_frequency: '1 fois/semaine',
      dental_health: 'Plusieurs implants',
      fracture_history: 'Côtes, radius gauche, vertèbres L2-L3 (2005)',
      other_comments_adult: 'Antécédents cardiovasculaires lourds, douleurs chroniques séquelles trauma',
      hasVisionCorrection: true,
      avatarUrl: null,
      cabinetId: null,
      userId: null
    },
    {
      id: crypto.randomUUID(),
      firstName: 'Léa',
      lastName: 'Lefebvre',
      gender: 'Femme',
      email: 'lea.lefebvre@example.com',
      phone: '06 90 12 34 56',
      birthDate: '1993-06-12',
      address: '11 Rue Rémusat',
      city: 'Toulouse',
      postalCode: '31000',
      osteopathId: userId,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      height: 170,
      weight: 62,
      bmi: 21.5,
      allergies: 'Aucune',
      currentTreatment: 'Aucun',
      isSmoker: false,
      isExSmoker: false,
      maritalStatus: 'PARTNERED',
      occupation: 'Infirmière (service urgences)',
      physicalActivity: 'Crossfit 3x/semaine',
      hasChildren: 'Non',
      handedness: 'RIGHT',
      generalPractitioner: 'Dr. Garnier',
      contraception: 'IUD_HORMONAL',
      surgicalHistory: 'RAS',
      gynecological_history: 'Cycles réguliers, DIU Mirena depuis 2020',
      traumaHistory: 'Entorse lombaire (2022)',
      rheumatologicalHistory: 'Lombalgie aiguë récidivante (port patients)',
      entProblems: 'RAS',
      digestiveProblems: 'RAS',
      intestinal_transit: 'Normal',
      sleep_quality: 'Variable (travail en horaires décalés)',
      sport_frequency: '3-4 fois/semaine',
      dental_health: 'Excellent',
      fracture_history: 'Aucune',
      other_comments_adult: 'Profession physique exigeante, lombalgies liées port de charges',
      hasVisionCorrection: false,
      avatarUrl: null,
      cabinetId: null,
      userId: null
    },
    {
      id: crypto.randomUUID(),
      firstName: 'Manon',
      lastName: 'Dubois',
      gender: 'Femme',
      email: 'manon.dubois@example.com',
      phone: '06 11 22 33 44',
      birthDate: '2015-03-20',
      address: '28 Rue des Écoles',
      city: 'Toulouse',
      postalCode: '31000',
      osteopathId: userId,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      height: 135,
      weight: 32,
      bmi: 17.6,
      allergies: 'Protéines lait de vache (diversification)',
      currentTreatment: 'Aucun (allergie résolue)',
      pediatrician_name: 'Dr. Blanchard',
      weight_at_birth: 3.2,
      height_at_birth: 49,
      apgar_score: '9/10',
      birthDetails: 'Accouchement voie basse, sans complications',
      pregnancyHistory: 'Grossesse normale, terme 39SA',
      developmentMilestones: 'Acquisition marche 12 mois, langage normal',
      fine_motor_skills: 'Excellente (dessin, écriture)',
      gross_motor_skills: 'Bonne coordination, aime grimper',
      childcare_type: 'École primaire',
      school_grade: 'CE2',
      sleepingPattern: 'Régulier, 10h/nuit',
      feeding: 'Appétit variable, quelques difficultés légumes',
      behavior: 'Enfant calme, concentrée, timide',
      childCareContext: 'Famille stable, mère enseignante',
      paramedical_followup: 'Orthophoniste (léger retard articulation)',
      dental_health: 'Suivi régulier, aucune carie',
      other_comments_child: 'Excellente élève, quelques maux de tête en fin de journée',
      hasVisionCorrection: false,
      avatarUrl: null,
      cabinetId: null,
      userId: null
    },
    {
      id: crypto.randomUUID(),
      firstName: 'Hugo',
      lastName: 'Gauthier',
      gender: 'Homme',
      email: 'hugo.gauthier@example.com',
      phone: '06 55 66 77 88',
      birthDate: '2018-09-10',
      address: '14 Avenue des Enfants',
      city: 'Toulouse',
      postalCode: '31000',
      osteopathId: userId,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString(),
      height: 105,
      weight: 18,
      bmi: 16.3,
      allergies: 'Aucune allergie connue',
      currentTreatment: 'Aucun',
      pediatrician_name: 'Dr. Mercier',
      weight_at_birth: 3.8,
      height_at_birth: 51,
      head_circumference: 52,
      apgar_score: '10/10',
      birthDetails: 'Césarienne programmée (siège), extraction facile',
      pregnancyHistory: 'Grossesse sans complication, présentation siège',
      developmentMilestones: 'Retournement 5 mois, marche 14 mois, langage en cours',
      fine_motor_skills: 'En développement (puzzles, dessin)',
      gross_motor_skills: 'Très bon équilibre, aime courir et sauter',
      childcare_type: 'Crèche puis école maternelle',
      school_grade: 'Grande section',
      sleepingPattern: 'Bon (11h/nuit + sieste occasionnelle)',
      feeding: 'Bon appétit, mange de tout',
      behavior: 'Enfant dynamique, curieux, sociable',
      childCareContext: 'Parents actifs, grands-parents proches',
      paramedical_followup: 'RAS',
      dental_health: 'Denture lactéale complète, bon état',
      other_comments_child: 'Enfant en pleine forme, quelques otites récidivantes petit',
      hasVisionCorrection: false,
      avatarUrl: null,
      cabinetId: null,
      userId: null
    }
  ];

  const appointments: Appointment[] = [];
  const invoices: Invoice[] = [];

  // Créer 30 consultations passées (sur les 12 derniers mois)
  const reasons = [
    'Douleurs lombaires',
    'Tensions cervicales',
    'Migraines',
    'Sciatique',
    'Entorse cheville',
    'Stress et anxiété',
    'Troubles du sommeil',
    'Douleurs épaule',
    'Suivi régulier',
    'Consultation post-opératoire'
  ];

  for (let i = 0; i < 30; i++) {
    const daysAgo = Math.floor(Math.random() * 365); // Derniers 12 mois
    const appointmentDate = new Date(now);
    appointmentDate.setDate(appointmentDate.getDate() - daysAgo);
    appointmentDate.setHours(9 + Math.floor(Math.random() * 9), [0, 15, 30, 45][Math.floor(Math.random() * 4)], 0, 0);

    const randomPatient = patients[Math.floor(Math.random() * patients.length)];
    const randomReason = reasons[Math.floor(Math.random() * reasons.length)];

    appointments.push({
      id: crypto.randomUUID(),
      patientId: randomPatient.id,
      osteopathId: userId,
      cabinetId: cabinetId,
      date: appointmentDate.toISOString(),
      status: 'COMPLETED',
      reason: randomReason,
      notes: `Consultation du ${appointmentDate.toLocaleDateString('fr-FR')}`,
      notificationSent: true,
      createdAt: appointmentDate.toISOString(),
      updatedAt: appointmentDate.toISOString()
    });
  }

  // Créer 28 factures correspondant aux consultations passées
  // Distribution : 22 payées, 4 en attente, 2 annulées (pour montrer toutes les fonctionnalités)
  const amounts = [55, 60, 65, 70];
  const paymentMethods = ['cash', 'check', 'card', 'transfer'];
  const invoiceStatuses: Array<'PAID' | 'PENDING' | 'CANCELED'> = [
    ...Array(22).fill('PAID'),      // 22 factures payées (≈79%)
    ...Array(4).fill('PENDING'),    // 4 factures en attente (≈14%)
    ...Array(2).fill('CANCELED')    // 2 factures annulées (≈7%)
  ];

  for (let i = 0; i < 28; i++) {
    const randomAppointment = appointments[i];
    const randomAmount = amounts[Math.floor(Math.random() * amounts.length)];
    const randomPayment = paymentMethods[Math.floor(Math.random() * paymentMethods.length)];
    const invoiceStatus = invoiceStatuses[i];

    invoices.push({
      id: crypto.randomUUID(),
      patientId: randomAppointment.patientId,
      appointmentId: randomAppointment.id,
      osteopathId: userId,
      cabinetId: cabinetId,
      invoiceNumber: `DEMO-${String(i + 1).padStart(3, '0')}`,
      date: randomAppointment.date,
      amount: randomAmount,
      paymentStatus: invoiceStatus,
      description: 'Consultation ostéopathie',
      paymentMethod: invoiceStatus === 'PAID' ? randomPayment as any : null,
      createdAt: randomAppointment.createdAt,
      updatedAt: randomAppointment.updatedAt
    });
  }

  // Ajouter 3 rendez-vous pour AUJOURD'HUI (à différentes heures)
  const todayTimes = [
    { hour: 9, minute: 0, status: 'COMPLETED' as const },
    { hour: 14, minute: 30, status: 'SCHEDULED' as const },
    { hour: 16, minute: 0, status: 'SCHEDULED' as const }
  ];

  todayTimes.forEach((time, index) => {
    const todayDate = new Date(now);
    todayDate.setHours(time.hour, time.minute, 0, 0);

    const randomPatient = patients[index % patients.length];

    appointments.push({
      id: crypto.randomUUID(),
      patientId: randomPatient.id,
      osteopathId: userId,
      cabinetId: cabinetId,
      date: todayDate.toISOString(),
      status: time.status,
      reason: reasons[index % reasons.length],
      notes: time.status === 'COMPLETED' ? 'Séance terminée' : '',
      notificationSent: true,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString()
    });
  });

  // Ajouter 5 rendez-vous futurs (J+1 à J+14)
  const futureDates = [1, 2, 5, 8, 14]; // jours dans le futur
  futureDates.forEach((daysLater, index) => {
    const futureDate = new Date(now);
    futureDate.setDate(futureDate.getDate() + daysLater);
    futureDate.setHours(9 + (index * 2), 0, 0, 0);

    const randomPatient = patients[(index + 3) % patients.length]; // Décaler pour varier les patients

    appointments.push({
      id: crypto.randomUUID(),
      patientId: randomPatient.id,
      osteopathId: userId,
      cabinetId: cabinetId,
      date: futureDate.toISOString(),
      status: 'SCHEDULED',
      reason: reasons[index % reasons.length],
      notes: '',
      notificationSent: false,
      createdAt: now.toISOString(),
      updatedAt: now.toISOString()
    });
  });

  console.log('🌱 [seedDemoData] Création des données démo pour cabinetId:', cabinetId);
  console.log('🏢 [seedDemoData] Cabinet créé:', cabinet);
  console.log('👤 [seedDemoData] Ostéopathe créé:', demoOsteopath);
  console.log('👥 [seedDemoData] Patients créés:', patients.length, '(dont 2 enfants)');
  console.log('📅 [seedDemoData] Rendez-vous créés:', appointments.length, `(30 passés + 3 aujourd'hui + 5 futurs)`);
  console.log('💰 [seedDemoData] Factures créées:', invoices.length, '(22 payées, 4 en attente, 2 en retard)');

  DemoStorage.set(cabinetId, 'osteopath', demoOsteopath);
  DemoStorage.set(cabinetId, 'cabinet', cabinet);
  DemoStorage.set(cabinetId, 'patients', patients);
  DemoStorage.set(cabinetId, 'appointments', appointments);
  DemoStorage.set(cabinetId, 'invoices', invoices);
  console.log('✅ [seedDemoData] Données démo créées avec succès');
}
