
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Utilisation de constantes pour les URLs et clés
// Ces valeurs peuvent être remplacées par des variables d'environnement dans le futur
const SUPABASE_URL = "https://jpjuvzpqfirymtjwnier.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwanV2enBxZmlyeW10anduaWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjg2Mzg4MjIsImV4cCI6MjA0NDIxNDgyMn0.VUmqO5zkRxr1Xucv556GStwCabvZrRckzIzXVPgAthQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: 'sb-jpjuvzpqfirymtjwnier-auth-token',
    flowType: 'pkce'
  }
});

// Exporter aussi les valeurs pour une utilisation ailleurs
export const SUPABASE_API_URL = SUPABASE_URL;
export const SUPABASE_API_KEY = SUPABASE_PUBLISHABLE_KEY;
